src/chart/urls.py
from django.conf.urls import url
from .views import TaskView
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^(?P<s_id>\d+)/$', TemplateView.as_view(template_name='gantt.html'), name='ganttchart'),
    url(r'^task/(?P<schedule_id>\d+)/$', TaskView.as_view())
]

src/projects/urls.py
from django.urls import path
from .view import *
app_name = "projects"

urlpatterns = [
    path('', index, name="index"),
    path('transfer', transfer, name="transfer"),
    path('<int:id>', get_project, name="get_project"),
    path('items/<int:id>', items, name="items"),
    path('item/<int:id>', get_project_item, name="get_project_item"),
    path('pending_material_report', pending_material_report,
         name="pending_material_report"),
    path('missing_material_report', missing_material_report,
         name="missing_material_report"),
    path('approval_request', approval_request, name="approval_request"),
    path('approve_item/<int:id>', approve_item, name="approve_item"),
    path('transfer_report', transfer_report, name="transfer_report"),
    path('pdf_report/<int:id>', pdf_report, name="pdf_report"),

    path('project_activity/<int:id>', get_project_activity,
         name="get_project_activity"),

    path('update_project_activity_plan', update_project_activity_plan,
         name="update_project_activity_plan"),
    path('excel_activity', excel_activity, name="excel_activity"),
    path('get_project_activity_plan_by_year_month', get_project_activity_plan_by_year_month,
         name="get_project_activity_plan_by_year_month"),
    path('project_activity', project_activity, name="project_activity"),
    path('create_activity', create_activity, name="create_activity"),
    path('edit_activity', edit_activity, name="edit_activity"),
    path('plans/<int:id>', plans, name="plans"),
    path('set_plan_fixed/<int:id>', set_plan_fixed, name="set_plan_fixed"),
    path('update_revisor/<int:id>', update_revisor, name="update_revisor"),
    path('get_project_activity_plan/<int:id>',
         get_project_activity_plan, name="get_project_activity_plan"),
    path('revise_plans', revise_plans, name="revise_plans"),
    path('revised_plan_report', revised_plan_report, name="revised_plan_report"),
    path('revise_plan/<int:id>', revise_plan, name="revise_plan"),
    path('chart_report', chart_report, name="chart_report"),
    path('edit_schedule_info', edit_schedule_info, name="edit_schedule_info"),
]

src/trackpot/urls.py
from django.contrib import admin
from django.urls import path, include
from projects.views import register_view
from projects.views import home_view, en_upload_SG_view
from django.contrib.auth import views as auth_views
from materials.views import register_store_view
from django.conf.urls import url
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from django.conf.urls.static import static
from chart.views import TaskView
from django.contrib.auth.decorators import login_required
from users.views import logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('register/', register_view, name='register'),
    path('home/', home_view, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),


    path('materials/',include('materials.urls')),
    path('purchase_orders/',include('purchase_orders.urls')),
    path('projects/',include('projects.urls')),




    # path('logout/',auth_views.LogoutView.as_view(template_name= 'users/logout.html'), name='logout'),
    # path('registerSpools/',register_spools_view , name='registerSpools'),
    # re_path(r'^(?P<page_id>[0-9]+)/$', subproject_view, name='pagedetail'),
    re_path('chart/', include('chart.urls'), name='ganttchart'),
    re_path(r'^task/(?P<schedule_id>\d+)/$',
            login_required(TaskView.as_view()), name='gchart'),
    re_path('storeview/', register_store_view, name='Store'),

    # url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    #  url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})

    #path('registerProject/',complete_project_view , name='Projectlist'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path(r'media/(?P<path>.*)$',
                serve, {'document_root': settings.MEDIA_ROOT, }),
    ]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += [
#         re_path(r'^media/(?P<path>.*)$', serve, {
#             'document_root': settings.MEDIA_ROOT,
#         }),
#     ]

src/projects/models.py
from django.db import models
from django.utils import timezone
from materials.models import Store
from django.conf import settings
from chart.models import Schedule
# Create your models here.


class Project(models.Model):
    receipt_number = models.CharField(max_length=32)
    contract_name = models.CharField(max_length=100, blank=True, null=True)
    description = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=191, blank=True, null=True)
    delivery_date = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    schedule = models.ForeignKey(
        Schedule, null=True, blank=True, on_delete=models.SET_NULL)
    assigned_for = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)


class ProjectItem(models.Model):
    quantity = models.IntegerField(default=0)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    item = models.ForeignKey(Store, on_delete=models.CASCADE, null=True)
    is_pending = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)


class ProjectMissingItem(models.Model):
    quantity = models.IntegerField(default=0)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    item = models.ForeignKey(Store, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)


class ProjectActivity(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)
    weightage = models.FloatField(blank=False, null=False)
    schedule = models.ForeignKey(
        Schedule, null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(default=timezone.now)
    revisor = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)


class ProjectActivityPlan(models.Model):
    plan_year = models.CharField(max_length=4, blank=False, null=False)
    plan_month = models.CharField(max_length=3, blank=False, null=False)
    plan_value = models.FloatField()
    actual_value = models.FloatField()
    is_plan_fixed = models.BooleanField(default=False)
    project_activity = models.ForeignKey(
        ProjectActivity, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)


class ProjectActivityPlanLog(models.Model):
    old_plan_value = models.FloatField()
    project_activity_plan = models.ForeignKey(
        ProjectActivityPlan, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)


class ScheduleInfo(models.Model):
    schedule = models.ForeignKey(
        Schedule, null=True, blank=True, on_delete=models.SET_NULL)
    project_description = models.CharField(
        max_length=191, blank=True, null=True)
    project_date = models.DateField(blank=True, null=True)
    weekly_progress = models.CharField(max_length=191, blank=True, null=True)
    cummlative_progress = models.CharField(
        max_length=191, blank=True, null=True)
    variance = models.CharField(max_length=191, blank=True, null=True)
    progress_statistic = models.CharField(
        max_length=191, blank=True, null=True)
    procurement = models.CharField(max_length=191, blank=True, null=True)
    mdr = models.CharField(max_length=191, blank=True, null=True)
    fabrication = models.CharField(max_length=191, blank=True, null=True)
    installation = models.CharField(max_length=191, blank=True, null=True)
    reason_for_variance = models.CharField(
        max_length=191, blank=True, null=True)
    detailed_progress_for_week = models.CharField(
        max_length=191, blank=True, null=True)
    planned_progress_for_next_week = models.CharField(
        max_length=191, blank=True, null=True)
    area_of_concerns = models.CharField(max_length=191, blank=True, null=True)


class ScheduleDocument(models.Model):
    schedule = models.ForeignKey(
        Schedule, null=True, blank=True, on_delete=models.SET_NULL)
    file_url = models.FileField(upload_to='schedule_files/')
    created_at = models.DateTimeField(default=timezone.now)

src/projects/views.py
from django.shortcuts import render,redirect
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from .forms import UserRegisterForm
from materials.forms import ProjectRegisterForm
# from materials.models import Proj
from chart.models import Schedule
from users.forms import UserRegisterForm
from django.contrib.auth.decorators import login_required


# Create your views here.
# def register_project_view(request,*args,**kwargs):

# 	if request.method=='POST':
# 			form = ProjectRegisterForm(request.POST)
# 			if form.is_valid():
# 				form.save()
				
# 				return redirect('RequirementList')
# 	else:
# 		form=ProjectRegisterForm()
# 	return form

@login_required()
def home_view(request,*args,**kwargs):
	# class table_view(ListView):
	# template_name="materials/listview.html"
	# queryset = Requirement.objects.all()
	schedule_list = Schedule.objects.filter(added_by=request.user)
	if not schedule_list:
		first_project = Schedule(name="Sample Project",is_selected=True,added_by=request.user,progress_schedule=0)
		first_project.save()
		print('saved')


	else:
		
		project_id = request.GET.get('project')
		first_project= schedule_list.first()
		first_project.is_selected=True
		first_project.save()
	
	project_selected = Schedule.objects.filter(added_by=request.user,is_selected=True)
	
	
	if request.method == 'GET' and 'project' in request.GET:
		q = request.GET['project']
		if q is not None and q != '':	
			project_selected = Schedule.objects.filter(added_by=request.user,id=project_id)
			for project in schedule_list:
				project.is_selected=False
				project.save()
			
				
			for project in project_selected:
				first_project.is_selected=False
				first_project.save()
				project.is_selected=True
				project.save()
	# object_list = Proj.objects.all()
			
	if request.method=='POST':
			form = ProjectRegisterForm(request.POST)
    
        	
			if form.is_valid():
				obj = form.save()
				obj.added_by = request.user
				obj.save()
				# return redirect('pagedetail', page_id=obj.id)
				return redirect('home')
	else:
		form=ProjectRegisterForm()

	if request.method=='POST':
			form1 = UserRegisterForm(request.POST)
			if form1.is_valid():
				save_it = form1.save()
				save_it.save()
				# subject="Thanks for registering with us"
				# message = "welcome "
				# from_email = settings.EMAIL_HOST_USER
				# to_list = [save_it.email , settings.EMAIL_HOST_USER]
				# send_mail(subject,message,from_email,to_list)
				# to turn off errors add fail_silently = True as an arguement to send_mail
				username=form1.cleaned_data.get('username');
				messages.success(request,f'Account created for {username}.')
				return redirect('home')
	else:
		form1=UserRegisterForm()
	selected_project= project_selected.first()

	context = {
	# 'object_list' : object_list,
	'form' : form,
	'form1' : form1,
	'schedule_list' : schedule_list,
	'project_selected' : project_selected,
	'project_list_first': selected_project

	}
	return render(request,"projects/home.html",context)

@login_required()
def en_upload_SG_view(request,*args,**kwargs):
	return render(request,"projects/en-upload-SG.html",{})
@login_required()
def register_view(request,*args,**kwargs):
	if request.method=='POST':
			form = UserRegisterForm(request.POST)
			if form.is_valid():
				save_it = form.save()
				save_it.save()
				subject="Thanks for registering with us"
				message = "welcome "
				from_email = settings.EMAIL_HOST_USER
				to_list = [save_it.email , settings.EMAIL_HOST_USER]
				send_mail(subject,message,from_email,to_list)
				# to turn off errors add fail_silently = True as an arguement to send_mail
				username=form.cleaned_data.get('username');
				messages.success(request,f'Account created for {username}.')
				return redirect('register')
	else:
		form=UserRegisterForm()
	return render(request,"projects/register.html",{'form':form})

src/projects/templates/projects/activity/activity_excel_view.html
{% extends 'loggedbase.html' %}
{% block title %}
Manage activity for {{schedule.name}}
{% endblock %}
{% block content %}
<style>
    .cell-border:hover {
        cursor: pointer;
        background: green;
    }
</style>
<div class="container-fluid form-group"><a href="{% url 'projects:chart_report' %}" class="btn btn-primary">Switch Chart
        Report</a></div>
<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body p-0">
                <form id="frm_project_activity" action="{% url 'projects:index' %}" method="POST" autocomplete="off"
                    novalidate>
                    {% csrf_token %}
                    <table class="table table-hover table-bordered table-sm m-0">
                        <thead>
                            <tr>
                                <th>Activity Name</th>
                                <th>Weightage</th>
                                <th class="text-center">Progress</th>
                                {% for list_year in list_years %}
                                <th class="text-center">{{list_year.0}}<br>{{list_year.1}}</th>
                                {% endfor %}
                            </tr>
                        </thead>
                        <tbody>
                            {% if activities %}
                            {% for activity in activities %}
                            <tr>
                                <td>{{ activity.project_activity.name }}</td>
                                <td>{{ activity.project_activity.weightage }}</td>
                                <td class="text-center">100</td>
                                {% for list_year in list_years %}
                                <td class="text-center cell-border"
                                    onclick="edit_plan('{{activity.project_activity.id}}','{{activity.project_activity.name}}','{{list_year.0}}','{{list_year.1}}')"
                                    id="plan_activity_{{activity.project_activity.id}}_{{list_year.0}}_{{list_year.1}}">
                                    {% for plan in activity.plans %}
                                    {% if plan.plan_year|stringformat:'s' == list_year.0|stringformat:'s' and plan.plan_month|stringformat:'s' == list_year.1|stringformat:'s' %}
                                    <span class="bg-warning badge p-2">{{plan.plan_value}}</span>
                                    <br><span class="bg-info badge mt-1 p-2">{{plan.actual_value}}</span>
                                    {% endif %}
                                    {% endfor %}
                                </td>
                                {% endfor %}
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="3" class="text-danger text-center">Project activity not found</td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</section>
<div class="modal" id="edit_plan_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="plan_title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="frm_project_activity" action="#" onsubmit="return false;" method="POST" autocomplete="off"
                novalidate>
                <div class="modal-body">
                    <input type="hidden" id="plan_activity_id" name="plan_activity_id">
                    <input type="hidden" id="plan_year" name="plan_year">
                    <input type="hidden" id="plan_month" name="plan_month">
                    <div class="form-group row">
                        <label>Plan Value</label>
                        <input type="text" id="plan_value" class="form-control" name="plan_value">
                    </div>
                    <div class="form-group row">
                        <label>Actual Value</label>
                        <input type="text" id="actual_value" class="form-control" name="actual_value">
                    </div>
                </div>
                <div class="modal-footer">
                    <a href-"javascript:void(0);" class="btn btn-primary" onclick="save_plan();">Save</a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    function edit_plan(id, plan_title, _year, _month) {
        $("#edit_plan_modal").modal('show');
        $("#edit_plan_modal #plan_title").html(plan_title + " " + _year + "-" + _month);
        $("#edit_plan_modal #plan_year").val(_year);
        $("#edit_plan_modal #plan_month").val(_month);
        $("#edit_plan_modal #plan_activity_id").val(id);
        $("#edit_plan_modal #plan_value").val('');
        $("#edit_plan_modal #actual_value").val('');
        $.getJSON("{% url 'projects:get_project_activity_plan_by_year_month' %}?id=" + id + "&plan_year=" + _year +
            "&plan_month=" + _month,
            function (data) {
                var _data = JSON.parse(data);
                var fields = _data[0]["fields"]
                $("#edit_plan_modal #plan_value").val(fields['plan_value']);
                $("#edit_plan_modal #actual_value").val(fields['actual_value']);
            })
    }

    function save_plan() {
        var plan_year = $("#edit_plan_modal #plan_year").val();
        var plan_month = $("#edit_plan_modal #plan_month").val();
        var plan_activity_id = $("#edit_plan_modal #plan_activity_id").val();
        var plan_value = $("#edit_plan_modal #plan_value").val();
        var actual_value = $("#edit_plan_modal #actual_value").val();
        $.getJSON("{% url 'projects:update_project_activity_plan' %}?plan_activity_id=" + plan_activity_id +
            "&plan_year=" + plan_year +
            "&plan_value=" + plan_value +
            "&actual_value=" + actual_value +
            "&plan_month=" + plan_month,
            function (data) {
                var _data = JSON.parse(data);
                var fields = _data[0]["fields"]
                $("#plan_activity_" + plan_activity_id + "_" + plan_year + "_" + plan_month).html('');
                $("#plan_activity_" + plan_activity_id + "_" + plan_year + "_" + plan_month).html(
                    '<span class="bg-warning badge p-2">' + fields['plan_value'] +
                    '</span><br><span class="bg-info badge mt-1 p-2">' + fields['actual_value'] + ' </span>');
                $("#edit_plan_modal").modal('hide');
            });
    }
</script>
{% endblock %}

src/projects/templates/projects/activity/approval_request.html
{% extends 'loggedbase.html' %}
{% block title %}
Approval Requested Materials
{% endblock %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body p-0">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th>Receipt No.</th>
                            <th>Item Name</th>
                            <th>Quantity</th>
                            <th width="30%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {%if pending_items %}
                        {% for pending_item in pending_items %}
                        <tr>
                            <td>{{ pending_item.project.receipt_number }}</td>
                            <td>{{ pending_item.item }}</td>
                            <td>{{ pending_item.quantity }}</td>
                            <td>
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" id="quantity_{{pending_item.id}}"
                                        value="{{pending_item.quantity}}">
                                    <div class="input-group-append">
                                        <a href="javascript:void(0);"
                                            onclick="update_status('{% url 'projects:approve_item' pending_item.id %}','{{pending_item.id}}')"
                                            class="btn btn-success">Make Approve</a>
                                        <a href="javascript:void(0);"
                                            onclick="update_reject_status('{% url 'projects:approve_item' pending_item.id %}','{{pending_item.id}}"
                                            class="btn btn-danger">Reject</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                        {%else%}
                        <tr>
                            <td colspan="4">Request not found</td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<script>
    function update_status(url, id) {
        var quantity = $("#quantity_" + id).val();
        if (quantity == '' && quantity == 0) {
            alert('Please enter the quantity')
        } else {
            window.open(url + "?quantity=" + quantity, '_blank');
        }
    }

    function update_reject_status(url, id) {
        window.open(url + "?quantity=0", '_blank');
    }
</script>
{% endblock %}

src/projects/templates/projects/activity/edit_schedule_info.html
{% extends 'loggedbase.html' %}
{% block title %}
Manage Project Items - {{schedule.name}} - {{project.receipt_number}}
{% endblock %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <b><a href="{% url 'projects:chart_report' %}" class="btn btn-link"><i class="fas fa-arrow-left"></i>
                Back</a></b>
        <div class="card">
            <div class="card-body p-0">
                {% for error in form.non_field_errors  %}
                <p class="text-danger text-center font-weight-bold mt-2">{{ error }}</p>
                {% endfor %}
                <form id="frm_edit_schedule" action="{% url 'projects:edit_schedule_info' %}" method="POST"
                    autocomplete="off" novalidate>
                    {% csrf_token %}
                    <div class="container mt-2 mb-2">
                        {{form.as_p}}
                        <input type="submit" name="submit" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

src/projects/templates/projects/activity/manage_activity.html
{% extends 'loggedbase.html' %}
{% block title %}
Manage activity for {{schedule.name}}
{% endblock %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        Revisor
        <select name="user_id" id="user_id" onchange="update_revisor(this.value);">
            <option value="">Select the Revisor</option>
            {%for user in users%}
            <option value="{{user.id}}" {% if revisor.revisor_id == user.id %}Selected{% endif %}>{{user.username}}
            </option>
            {%endfor%}
        </select>
        <a href="{% url 'projects:excel_activity' %}" class="btn btn-info">Switch Excel View</a>
        <a href="{% url 'projects:chart_report' %}" class="btn btn-primary">Chart Report</a>
        {% comment %} <a href="{% url 'projects:edit_activity' %}" class="btn btn-default">Edit Activity</a>
        {% endcomment %}
        <br>
        <br>
        <div class="card">
            <div class="card-body p-0">
                <h5 class="pt-2 pl-2"><i class="fa fa-search"></i> Search Activity</h5>
                <hr>
                <form class="form-horizontal p-2" action="{% url 'projects:project_activity' %}" method="GET"
                    autocomplete="off" novalidate>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="">Activity Name</label>
                                <input type="text" id="name" name="name" class="form-control"
                                    value="{{request.GET.name}}" />
                            </div>
                        </div>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Search</button>
                        <a href="{% url 'projects:project_activity' %}" class="btn btn-default btn-outline">Reset</a>
                    </div>
                </form>
                {% if total_weightage.weightage__sum > 100 %}
                <h4 class="text-danger text-center font-weight-bold">Total Weightage is
                    {{total_weightage.weightage__sum}}</h4>
                {% else %}
                <h4 class="text-success text-center font-weight-bold">Total Weightage is
                    {{total_weightage.weightage__sum}}</h4>
                {% endif %}
                <form id="frm_project" action="{% url 'projects:project_activity' %}" method="POST" autocomplete="off"
                    novalidate>
                    {% csrf_token %}
                    <table class="table table-sm">
                        <tr>
                            <input type="hidden" id="_id" name="_id" value="{{initial_id}}">
                            <input type="hidden" id="revisor_id" name="revisor_id" value="{{revisor.revisor_id}}">
                            <th>{{form.name}}<span class="text-danger text-sm">{{form.name.errors.as_text}}</span>
                            </th>
                            <th>{{form.weightage}}<span
                                    class="text-danger text-sm">{{form.weightage.errors.as_text}}</span>
                            </th>
                            <th><input type="submit" name="" id="" class="btn btn-primary" value="Save"></th>
                        </tr>
                        <thead>
                            <tr>
                                <th>Activity Name</th>
                                <th>Weightage</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if project_activities%}
                            {% for project_activity in project_activities %}
                            <tr>
                                <td>{{ project_activity.name }}</td>
                                <td>{{ project_activity.weightage }}</td>
                                <td class="text-center">
                                    <i class="fa fa-pencil"
                                        onclick="edit_project_activity('{% url 'projects:get_project_activity' project_activity.id %}')"></i>
                                    <a href="{% url 'projects:plans' project_activity.id %}"><i
                                            class="ml-2 fa fa-link"></i> View Plans</a>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="3" class="text-danger text-center">Project activity not found</td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</section>
<script>
    function update_revisor(user) {
        if (user != "") {
            window.location = "{% url 'projects:update_revisor' schedule.id %}?user_id=" + user;
        }
    }
</script>
<script>
    function edit_project_activity(url) {
        $.getJSON(url,
            function (data) {
                var _data = JSON.parse(data);
                var __data = _data[0]['fields'];
                $("#_id").val(_data[0]['pk']);
                $("#id_name").val(__data.name);
                $("#id_weightage").val(__data.weightage);
            })
    }
</script>
{% endblock %}