src/chart/urls.py
from django.conf.urls import url
from .views import TaskView
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^(?P<s_id>\d+)/$', TemplateView.as_view(template_name='gantt.html'), name='ganttchart'),
    url(r'^task/(?P<schedule_id>\d+)/$', TaskView.as_view())
]

src/materials/urls.py
from django.urls import path
from .view import index, get_material, excel_export
app_name = "materials"

urlpatterns = [
    path('', index, name="index"),
    path('<int:id>', get_material, name="get_material"),
    path('excel_export', excel_export, name="excel_export"),
]

src/projects/urls.py
from django.urls import path
from .view import *
app_name = "projects"

urlpatterns = [
    path('', index, name="index"),
    path('transfer', transfer, name="transfer"),
    path('<int:id>', get_project, name="get_project"),
    path('items/<int:id>', items, name="items"),
    path('item/<int:id>', get_project_item, name="get_project_item"),
    path('pending_material_report', pending_material_report,
         name="pending_material_report"),
    path('missing_material_report', missing_material_report,
         name="missing_material_report"),
    path('approval_request', approval_request, name="approval_request"),
    path('approve_item/<int:id>', approve_item, name="approve_item"),
    path('transfer_report', transfer_report, name="transfer_report"),
    path('pdf_report/<int:id>', pdf_report, name="pdf_report"),

    path('project_activity/<int:id>', get_project_activity,
         name="get_project_activity"),

    path('update_project_activity_plan', update_project_activity_plan,
         name="update_project_activity_plan"),
    path('excel_activity', excel_activity, name="excel_activity"),
    path('get_project_activity_plan_by_year_month', get_project_activity_plan_by_year_month,
         name="get_project_activity_plan_by_year_month"),
    path('project_activity', project_activity, name="project_activity"),
    path('create_activity', create_activity, name="create_activity"),
    path('edit_activity', edit_activity, name="edit_activity"),
    path('plans/<int:id>', plans, name="plans"),
    path('set_plan_fixed/<int:id>', set_plan_fixed, name="set_plan_fixed"),
    path('update_revisor/<int:id>', update_revisor, name="update_revisor"),
    path('get_project_activity_plan/<int:id>',
         get_project_activity_plan, name="get_project_activity_plan"),
    path('revise_plans', revise_plans, name="revise_plans"),
    path('revised_plan_report', revised_plan_report, name="revised_plan_report"),
    path('revise_plan/<int:id>', revise_plan, name="revise_plan"),
    path('chart_report', chart_report, name="chart_report"),
    path('edit_schedule_info', edit_schedule_info, name="edit_schedule_info"),
]

src/purchase_orders/urls.py
from django.urls import path
from .views import index, get_purchase_order, items, get_purchase_order_item, report, addition_report, pdf_report
app_name = "purchase_orders"

urlpatterns = [
    path('', index, name="index"),
    path('<int:id>', get_purchase_order, name="get_purchase_order"),
    path('items/<int:id>', items, name="items"),
    path('item/<int:id>', get_purchase_order_item, name="get_purchase_order_item"),
    path('report', report, name="report"),
    path('addition_report', addition_report, name="addition_report"),
    path('pdf_report/<int:id>', pdf_report, name="pdf_report"),
]

src/trackpot/urls.py
from django.contrib import admin
from django.urls import path, include
from projects.views import register_view
from projects.views import home_view, en_upload_SG_view
from django.contrib.auth import views as auth_views
from materials.views import register_store_view
from django.conf.urls import url
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from django.conf.urls.static import static
from chart.views import TaskView
from django.contrib.auth.decorators import login_required
from users.views import logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('register/', register_view, name='register'),
    path('home/', home_view, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),


    path('materials/',include('materials.urls')),
    path('purchase_orders/',include('purchase_orders.urls')),
    path('projects/',include('projects.urls')),




    # path('logout/',auth_views.LogoutView.as_view(template_name= 'users/logout.html'), name='logout'),
    # path('registerSpools/',register_spools_view , name='registerSpools'),
    # re_path(r'^(?P<page_id>[0-9]+)/$', subproject_view, name='pagedetail'),
    re_path('chart/', include('chart.urls'), name='ganttchart'),
    re_path(r'^task/(?P<schedule_id>\d+)/$',
            login_required(TaskView.as_view()), name='gchart'),
    re_path('storeview/', register_store_view, name='Store'),

    # url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    #  url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})

    #path('registerProject/',complete_project_view , name='Projectlist'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path(r'media/(?P<path>.*)$',
                serve, {'document_root': settings.MEDIA_ROOT, }),
    ]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += [
#         re_path(r'^media/(?P<path>.*)$', serve, {
#             'document_root': settings.MEDIA_ROOT,
#         }),
#     ]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <title>Trackpot</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!--   <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--===============================================================================================-->
  <link rel="icon" type="image/png" href="../../static/login/images/icons/favicon.ico" />
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="../../static/login/vendor/bootstrap/css/bootstrap.min.css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="../../static/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="../../static/login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="../../static/login/vendor/animate/animate.css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="../../static/login/vendor/css-hamburgers/hamburgers.min.css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="../../static/login/vendor/animsition/css/animsition.min.css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="../../static/login/vendor/select2/select2.min.css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="../../static/login/vendor/daterangepicker/daterangepicker.css">
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="../../static/login/css/util.css">
  <link rel="stylesheet" type="text/css" href="../../static/login/css/main.css">
  <style type="text/css">
    body {}
  </style>

</head>

<body>

  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark "
    style="background-image:linear-gradient(to right, #003366,rgb(0,92,151), #4682B4,lightblue)">
    <a class="navbar-brand" href="#" style="color:white">
      <h1><strong>Trackpott</strong></h1>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">


      </ul>

    </div>
  </nav>




  <div class="limiter">
    <div class="container-login100">
      <div class="wrap-login100">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success" style="margin-top: 70px;">
          {{message}}
        </div>
        {% endfor  %}
        {% endif %}

        {%block content %}


        {%endblock%}
        <!-- <div class="login100-more" style="background-image:linear-gradient(to right, #003366,rgb(0,92,151), #4682B4,lightblue));">
        </div> -->
        <!-- div class="login100-more" style="background-color:blue;">
        </div> -->
      </div>
    </div>
  </div>


  <script src="../../static/login/vendor/jquery/jquery-3.2.1.min.js"></script>
  <!--===============================================================================================-->
  <script src="../../static/login/vendor/animsition/js/animsition.min.js"></script>
  <!--===============================================================================================-->
  <script src="../../static/login/vendor/bootstrap/js/popper.js"></script>
  <script src="../../static/login/vendor/bootstrap/js/bootstrap.min.js"></script>
  <!--===============================================================================================-->
  <script src="../../static/login/vendor/select2/select2.min.js"></script>
  <!--===============================================================================================-->
  <script src="../../static/login/vendor/daterangepicker/moment.min.js"></script>
  <script src="../../static/login/vendor/daterangepicker/daterangepicker.js"></script>
  <!--===============================================================================================-->
  <script src="../../static/login/vendor/countdowntime/countdowntime.js"></script>
  <!--===============================================================================================-->
  <script src="../../static/login/js/main.js"></script>


  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>
</body>

</html>

src/templates/loggedbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Trackpott</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'admin/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'admin/dist/css/adminlte.min.css' %}">

  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">


</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <!--       <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li> -->
      </ul>

      <!-- SEARCH FORM -->
      <!--     <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
 -->
      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <!-- Messages Dropdown Menu -->
        <li>Welcome {{request.user}}</li>
      </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a href="#" class="brand-link">
        <img src="{% static 'logo.png'%}" class="brand-image img-circle elevation-2">

        <span class="brand-text font-weight-light">Trackpott</span>
      </a>

      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <!-- <div class="image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div> -->
          <!-- <div class="info">
          <a href="#" class="d-block">{{request.user}}</a>
        </div>
      </div> -->

          <!-- Sidebar Menu -->
          <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
              <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
              <li class="nav-item has-treeview menu-open">
                <a href="{% url 'home' %}" class="nav-link active">
                  <i class="nav-icon fas fa-tachometer-alt"></i>
                  <p>
                    DASHBOARD
                    <!--                 <i class="right fas fa-angle-left"></i> -->
                  </p>
                </a>
                <!-- <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="./index.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dashboard v1</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="./index2.html" class="nav-link active">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dashboard v2</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="./index3.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dashboard v3</p>
                </a>
              </li>
            </ul> -->
              </li>
              <!-- <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Widgets
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li> -->
              <li class="nav-item">
                <a href="{% url 'projects:project_activity' %}" class="nav-link">
                  <i class="nav-icon fas fa-calendar-alt"></i>
                  <p>Project Activity</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'projects:revise_plans' %}" class="nav-link">
                  <i class="nav-icon fas fa-calendar-alt"></i>
                  <p>Revise Plans</p>
                </a>
              </li>
              <li class="nav-item has-treeview">

                {% block link %}{% endblock %}

                <i class="nav-icon fas fa-calendar-alt"></i>
                <p>
                  SCHEDULE
                </p>
                </a>

              </li>
              <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                  <i class="nav-icon fas fa-store"></i>
                  <p>
                    Store
                    <i class="right fas fa-angle-left"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>
                        Mechanical
                        <i class="right fas fa-angle-left"></i>
                      </p>
                    </a>
                    <ul class="nav nav-treeview">
                      <li class="nav-item">
                        <a href="{% url 'materials:index'%}" class="nav-link">
                          <i class="far fa-dot-circle nav-icon"></i>
                          <p>Materials</p>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="{% url 'purchase_orders:index'%}" class="nav-link">
                          <i class="far fa-dot-circle nav-icon"></i>
                          <p>Purchase Orders</p>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="{% url 'projects:index'%}" class="nav-link">
                          <i class="far fa-dot-circle nav-icon"></i>
                          <p>Project Transfers</p>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="{% url 'projects:approval_request'%}" class="nav-link">
                          <i class="far fa-dot-circle nav-icon"></i>
                          <p>Approval Requests</p>
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>
                        Electrical
                        {% comment %} <i class="right fas fa-angle-left"></i> {% endcomment %}
                      </p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>
                        Instrumentation
                        {% comment %} <i class="right fas fa-angle-left"></i> {% endcomment %}
                      </p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                  <i class="nav-icon fas fa-book"></i>
                  <p>
                    REPORTS
                    <i class="right fas fa-angle-left"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'purchase_orders:addition_report' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Material Addition Report</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'projects:transfer_report' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Material Transfer Report</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'projects:pending_material_report' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Pending Material Report</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'projects:missing_material_report' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Missing Material Report</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'purchase_orders:report' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>PO Report</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'projects:revised_plan_report' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Revised Plan Report</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="pages/charts/chartjs.html" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Contract Copy</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="pages/charts/flot.html" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Engineering Package</p>
                    </a>
                  </li>

                </ul>
              </li>



              <li class="nav-header" style="color: #343a40">MULTI LEVEL EXAMPLE 1234</li>
              <a href="{% url 'logout'%}" class="btn btn-outline-success my-2 my-sm-0"
                style="background-color: white; color: black; border-color: white; width:50%;margin-left:15%; margin-bottom: 20%">Logout</a>





            </ul>
          </nav>
          <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">

          <div style="text-align: center;">
            <h1 class="m-0 text-dark">{% block title%} {% endblock %}</h1>
          </div><!-- /.col -->
          <!-- /.col -->
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->
      {% block content %}

      {% endblock%}
    </div>
    <!-- Main Footer -->

  </div>
  <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->
  <!-- jQuery -->
  <script src="{% static 'admin/plugins/jquery/jquery.min.js' %}"></script>

  <!-- Bootstrap -->
  <script src="{% static 'admin/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- overlayScrollbars -->
  <script src="{% static 'admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>

  <!-- AdminLTE App -->

  <script src="{% static 'admin/dist/js/adminlte.js' %}"></script>


  <!-- OPTIONAL SCRIPTS -->

  <script src="{% static 'admin/dist/js/demo.js' %}"></script>

  <!-- PAGE PLUGINS -->
  <!-- jQuery Mapael -->
  <script src="{% static 'admin/plugins/jquery-mousewheel/jquery.mousewheel.js' %}"></script>
  <script src="{% static 'admin/plugins/raphael/raphael.min.js' %}"></script>
  <script src="{% static 'admin/plugins/jquery-mapael/jquery.mapael.min.js' %}"></script>
  <script src="{% static 'admin/plugins/jquery-mapael/maps/usa_states.min.js' %}"></script>

  <!-- ChartJS -->
  <script src="{% static 'admin/plugins/chart.js/Chart.min.js' %}"></script>

  <!-- PAGE SCRIPTS -->
  <script src="{% static 'admin/dist/js/pages/dashboard2.js' %}"></script>
  {% block js_scripts %}
  {% endblock %}
</body>

</html>