src/chart/urls.py
from django.conf.urls import url
from .views import TaskView
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^(?P<s_id>\d+)/$', TemplateView.as_view(template_name='gantt.html'), name='ganttchart'),
    url(r'^task/(?P<schedule_id>\d+)/$', TaskView.as_view())
]

src/materials/urls.py
from django.urls import path
from .view import index, get_material, excel_export
app_name = "materials"

urlpatterns = [
    path('', index, name="index"),
    path('<int:id>', get_material, name="get_material"),
    path('excel_export', excel_export, name="excel_export"),
]

src/trackpot/urls.py
from django.contrib import admin
from django.urls import path, include
from projects.views import register_view
from projects.views import home_view, en_upload_SG_view
from django.contrib.auth import views as auth_views
from materials.views import register_store_view
from django.conf.urls import url
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from django.conf.urls.static import static
from chart.views import TaskView
from django.contrib.auth.decorators import login_required
from users.views import logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('register/', register_view, name='register'),
    path('home/', home_view, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),


    path('materials/',include('materials.urls')),
    path('purchase_orders/',include('purchase_orders.urls')),
    path('projects/',include('projects.urls')),




    # path('logout/',auth_views.LogoutView.as_view(template_name= 'users/logout.html'), name='logout'),
    # path('registerSpools/',register_spools_view , name='registerSpools'),
    # re_path(r'^(?P<page_id>[0-9]+)/$', subproject_view, name='pagedetail'),
    re_path('chart/', include('chart.urls'), name='ganttchart'),
    re_path(r'^task/(?P<schedule_id>\d+)/$',
            login_required(TaskView.as_view()), name='gchart'),
    re_path('storeview/', register_store_view, name='Store'),

    # url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    #  url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})

    #path('registerProject/',complete_project_view , name='Projectlist'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path(r'media/(?P<path>.*)$',
                serve, {'document_root': settings.MEDIA_ROOT, }),
    ]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += [
#         re_path(r'^media/(?P<path>.*)$', serve, {
#             'document_root': settings.MEDIA_ROOT,
#         }),
#     ]

src/chart/models.py
import os
from django.db import models
from django.utils.translation import ugettext_lazy as _
from treebeard.mp_tree import MP_Node
from django.contrib.auth.models import AbstractBaseUser
from django.conf import settings
from materials.models import Store
from django.utils import timezone
# Create your models here.


def get_new_static_resource_path(instance, filename, folder_name=''):
    return os.path.join(folder_name, filename)


def get_new_task_file_resource_path(instance, filename):
    return get_new_static_resource_path(instance, filename, 'task')

class Schedule(models.Model):
    name = models.CharField(max_length=250, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    duration = models.IntegerField(default=0)
    start_date = models.DateField(null=True,default=None, blank=True)
    end_date = models.DateField(null=True,default=None, blank=True)
    is_selected = models.BooleanField(default=False)
    can_write = models.BooleanField(default=True)
    can_write_on_parent = models.BooleanField(default=False)
    selected_row = models.IntegerField(default=0)
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL,null=True, blank=True, on_delete=models.SET_NULL)
    progress_schedule= models.FloatField(null=True,blank=True)

    def __str__(self):
        return u'%s' % (
            self.name,
        )


# class MileStone(BaseGanttModel):
#     schedule = models.ForeignKey('Schedule', null=True, blank=True)
#
#     def __unicode__(self):
#         return u'%s' % (
#             self.name,
#         )
class Roles(models.Model):
    name = models.CharField('Name', max_length=30, blank=True)


class Resource(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, _('Male')),
        (FEMALE, _('Female')),
    )
    # Fields

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=1,
                              blank=True, null=True)
    role = models.ForeignKey('Roles', null=True, blank=True,on_delete=models.CASCADE)
    effort = models.IntegerField(default=0)


class Task(models.Model):
    name = models.CharField(max_length=250, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    duration = models.IntegerField(default=0)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children',on_delete=models.CASCADE)
    level = models.IntegerField(default=0)
    depends = models.CharField(max_length=300, null=True,blank=True)
    schedule = models.ForeignKey('Schedule', null=True, blank=True,on_delete=models.CASCADE)
    is_milestone = models.BooleanField(default=False)
    end_is_milestone = models.BooleanField(default=False)
    resources = models.ManyToManyField('Resource', blank=True)
    status = models.CharField(max_length=300,blank=True, null=True)
    progress = models.DecimalField(decimal_places=2, default=0, max_digits=10)
    remarks = models.CharField(max_length=300, null=True,blank=True)
    task_file = models.FileField(
        upload_to=get_new_task_file_resource_path,
        null=True,
        blank=True,
        verbose_name=_("Task file")
    )

    def __str__(self):
        return 'Task: %s' % self.name

src/materials/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class Store(models.Model):
    item_s = models.CharField(max_length=100)
    spec_s = models.CharField(max_length=100)
    material_s = models.CharField(max_length=100)
    rating_s = models.CharField(max_length=100, blank=True, null=True)
    size1_s = models.IntegerField(blank=True, null=True)
    sch1_s = models.IntegerField(blank=True, null=True)
    size2_s = models.IntegerField(blank=True, null=True)
    sch2_s = models.IntegerField(blank=True, null=True)
    facing_s = models.CharField(max_length=100, blank=True, null=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.item_s)

    def item_name(self):
        return str(str(self.item_s)+' / '+str(self.spec_s)+' / '+str(self.material_s)+' / '+str(self.rating_s)+' / '+str(self.size1_s)+' / '+str(self.sch1_s)+' / '+str(self.size2_s)+' / '+str(self.sch2_s)+' / '+str(self.facing_s))

src/materials/forms.py
from django import forms
from chart.models import Schedule
from .models import Store


class MaterialForm(forms.ModelForm):
    item_s = forms.CharField(required=True,label='Item',max_length="100",widget=forms.TextInput(attrs={'class': 'form-control'}))
    spec_s = forms.CharField(required=False,label='Spec',max_length="100",widget=forms.TextInput(attrs={'class': 'form-control'}))
    material_s = forms.CharField(required=True,label='Material',max_length="100",widget=forms.TextInput(attrs={'class': 'form-control'}))
    rating_s = forms.CharField(required=False,label='',max_length="100",widget=forms.TextInput(attrs={'class': 'form-control'}))
    size1_s = forms.IntegerField(required=True,label='',widget=forms.TextInput(attrs={'class': 'form-control'}))
    sch1_s = forms.IntegerField(required=False,label='',widget=forms.TextInput(attrs={'class': 'form-control'}))
    size2_s = forms.IntegerField(required=False,label='',widget=forms.TextInput(attrs={'class': 'form-control'}))
    sch2_s = forms.IntegerField(required=False,label='',widget=forms.TextInput(attrs={'class': 'form-control'}))
    facing_s = forms.CharField(required=True,label='',max_length="100",widget=forms.TextInput(attrs={'class': 'form-control'}))
    
    class Meta:
        model=Store
        fields = ["item_s","spec_s","material_s","rating_s","size1_s","sch1_s","size2_s","sch2_s","facing_s"]

    def clean(self):
        rating = self.cleaned_data.get("rating_s")
        sch1 = self.cleaned_data.get("sch1_s")
        if rating is None:
            if sch1 is None:
                raise forms.ValidationError("Schedule 1 field is required!")
        if sch1 is None:
            if rating is None:
                raise forms.ValidationError("Rating field is required!")

class StoreRegisterForm(forms.ModelForm):


    class Meta:
        model=Store
        fields= ["item_s",'spec_s',
                "material_s",
                "rating_s",
                "size1_s" ,
                "sch1_s",
                "size2_s",
                "sch2_s",
                "facing_s",
            ]





class ProjectRegisterForm(forms.ModelForm):


    class Meta:
        model=Schedule
        fields= ['name','start_date','end_date','progress_schedule']

src/materials/views.py
from django.shortcuts import render, redirect, render_to_response
from .forms import ProjectRegisterForm, StoreRegisterForm
from django.views.generic import ListView, CreateView, TemplateView
from .models import Store
from django.forms import modelformset_factory
from django.contrib.auth.decorators import login_required
from datetime import date
# from fpdf import FPDF
from django.urls import reverse
from django.http import HttpResponseRedirect
from io import BytesIO
from django.core.files import File
from django.contrib import messages
from chart.models import Schedule
# from .utils import render_to_pdf
# from .forms import UploadFileForm

# from chartit import DataPool, Chart, PivotDataPool, PivotChart
# Create your views here.


@login_required()
def register_store_view(request, *args, **kwargs):
    project_selected = Schedule.objects.filter(
        added_by=request.user, is_selected=True)
    selected_project = project_selected.first()

    object_list = Store.objects.filter()

    if request.method == 'POST':
        form1 = StoreRegisterForm(request.POST, request.FILES)
        if form1.is_valid():
            obj = form1.save()
            obj.save()

            messages.success(request, 'Report generated')

            return HttpResponseRedirect(reverse('Store', args=()))
    else:
        form1 = StoreRegisterForm()
    return render(request, "materials/listviewStore.html", {'form1': form1, 'object_list': object_list, 'project_list_first': selected_project})



# class table_view(ListView):
# 	template_name="materials/listview.html"
# 	queryset = Requirement.objects.all()

# 	if request.method=='POST':
# 			form = MaterialRegisterForm(request.POST)
# 			if form.is_valid():
# 				form.save()
# 				username=form.cleaned_data.get('username');

# 				return redirect('RequirementList')
# 	else:
# 		form=MaterialRegisterForm()
# 	return render(request,"materials/listview.html",{'form':form })


@login_required()
def subproject_view(request, page_id):
    obj = Proj.objects.get(id=page_id)

    SubprojectFormset = modelformset_factory(
        Subproj, fields=('name', 'plan_date', 'complete_date'))
    # ACTIVITES FORMSET
    if request.method == 'POST':
        # formset = SubprojectFormset(request.POST , queryset=Subproj.objects.filter(proj_id =obj.id , is_subproj = False))
        formset = SubprojectFormset(
            request.POST, queryset=Subproj.objects.filter(proj_id=obj.id))
        if formset.is_valid():
            instances = formset.save(commit=False)
            for instance in instances:
                instance.proj_id = obj.id
                # instance.is_subproj = False
                instance.save()
            return redirect('pagedetail', page_id=obj.id)
    # formset = SubprojectFormset(queryset=Subproj.objects.filter(proj_id=obj.id , is_subproj=False))
    formset = SubprojectFormset(
        queryset=Subproj.objects.filter(proj_id=obj.id))
    # SUBPROJECT FORMSET

    # if request.method == 'POST':
    # 	formset2 = SubprojectFormset(request.POST , queryset=Subproj.objects.filter(proj_id =obj.id , is_subproj=True))
    # 	if formset2.is_valid():
    # 		instances2 = formset2.save(commit = False)
    # 		for instance2 in instances2:
    # 			instance2.proj_id = obj.id
    # 			instance2.is_subproj = True
    # 			instance2.save()
    # 		return redirect('pagedetail',page_id=obj.id)
    # formset2 = SubprojectFormset(queryset=Subproj.objects.filter(proj_id=obj.id, is_subproj=True))

    # sales = DataPool(
    #    series=
    #     [{'options': {
    #     #    'source': SalesReport.objects.all()},
    #     'source': Subproj.objects.filter(proj_id = obj.id)},
    #     #'source': SalesReport.objects.filter(sales__lte=10.00)},
    #         'terms': [{'name': 'name',
    #         'days': 'days'}]
    #         },
    #     ])

    # cht = Chart(
    #    	datasource = sales,
    #     series_options =
    #       [{'options':{
    #           'type': 'column',
    #           'stacking': False},
    #         'terms':{
    #           'name': [
    #             'days']
    #         }}],
    #     chart_options =
    #       {'title': {
    #            'text': 'Activity Days'},
    #        'xAxis': {
    #            'title':{'text': 'Activity name'}},
    #        'yAxis': {
    #            'title': {'text': 'Number of days'}},
    #        })

    # qs = Subproj.objects.filter(proj_id = obj.id)

    # import plotly.figure_factory as ff
    # from plotly.offline import plot

    # df = [dict(Task="Job A", Start='2009-01-01', Finish='2009-02-28'),
    #       dict(Task="Job B", Start='2009-03-05', Finish='2009-04-15'),
    #       dict(Task="Job C", Start='2009-02-20', Finish='2009-05-30')]

    # fig = ff.create_gantt(df)
    # figure = plot(fig)

    context = {
        "object": obj,
        'formset': formset,
        # 'chart_list' : cht,
        # 'qs':qs,
        # 'graph':figure,
        # 'formset2': formset2
    }
    return render_to_response('materials/create_subproject.html', context)
    # return render(request,"materials/create_subproject.html",context)

src/materials/templates/materials/listviewDocsss.html
{% extends 'loggedbase.html' %}
{% load mathfilters %}
{% block title %}
Master Document Register
{% endblock %}
{% block link %} <a href="{% url 'ganttchart' project_list_first.id %}" class="nav-link" target="_blank">{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<style type="text/css">
/*tr,td,th{
    background-color: white;
}*/
.card{
    width:170%;
}
</style>
<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body p-0">
                <h5 class="pt-2 pl-2"><i class="fa fa-search"></i> Search Document</h5>
                <hr>
                <form class="form-horizontal p-2" action="{% url 'materials:documentview' %}" method="GET" autocomplete="off"
                    novalidate>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="">DOC NO</label>
                                <input type="text" id="ADNOC_documentno" name="ADNOC_documentno" class="form-control"
                                    value="{{request.GET.ADNOC_documentno}}" />
                            </div>
                        </div>
                        <!-- <div class="col-md-3">
                            <div class="form-group">
                                <label for="">Material</label>
                                <input type="text" id="material_s" name="material_s" class="form-control"
                                    value="{{request.GET.material_s}}" />
                            </div>
                        </div> -->
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Search</button>
                        <a href="{% url 'materials:documentview' %}" class="btn btn-default btn-outline">Reset</a>
                        <a href="{% url 'materials:excel_export_doc' %}" target="_blank" class="btn btn-success"><i
                                class="fa fa-file-pdf-o"></i> Export Excel</a>
                    </div>
                </form>
                <form id="frm_material" method="POST" action="{% url 'document' %}"  enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table table-sm">
 
                        <tr>
                            <input type="hidden" id="_id" name="_id" value="{{initial_id}}" >
                           
                            <th>{{form.ADNOC_documentno}}<span class="text-danger text-sm">{{form.ADNOC_documentno.errors.as_text}}</span>
                            </th>
                            <th>{{form.description}}<span class="text-danger text-sm">{{form.description.errors.as_text}}</span>
                            </th>
                            <th>{{form.revision}}<span class="text-danger text-sm">{{form.revision.errors.as_text}}</span>
                            </th>
                            <th>{{form.due_date}}<span class="text-danger text-sm">{{form.due_date.errors.as_text}}</span>
                            </th>
                            <th>{{form.submission_date}}<span class="text-danger text-sm">{{form.submission_date.errors.as_text}}</span>
                            </th>
                            <th>{{form.transmittal_number}}<span
                                    class="text-danger text-sm">{{form.transmittal_number.errors.as_text}}</span>
                            <th>{{form.reason_of_issue}}<span
                                    class="text-danger text-sm">{{form.reason_of_issue.errors.as_text}}</span>
                            <th>{{form.document}}<span
                                    class="text-danger text-sm">{{form.document.errors.as_text}}</span>
                            <th>{{form.aprroval_date}}<span
                                    class="text-danger text-sm">{{form.aprroval_date.errors.as_text}}</span>
                            <th>{{form.receipt_transmittalno}}<span
                                    class="text-danger text-sm">{{form.receipt_transmittalno.errors.as_text}}</span>
                            </th>
                            <th>{{form.view_response}}<span
                                    class="text-danger text-sm">{{form.view_response.errors.as_text}}</span>
                            </th>
                            <th>{{form.aprroval_code}}<span
                                    class="text-danger text-sm">{{form.aprroval_code.errors.as_text}}</span>
                            </th>
                            <th>{{form.remarks}}<span
                                    class="text-danger text-sm">{{form.remarks.errors.as_text}}</span>
                            </th>

                            <th><input type="submit" name="" id="" class="btn btn-primary" value="Save"></th>
                        </tr>
                        <thead>
                            <tr>
                                    <th>DOC NO.</th>                                                                   
                                    <th>DESCRIPTION</th>
                                    <th>REVISION</th>
                                    <th>DUE DATE</th>
                                    <th>SUBMISSION DATE</th>
                                    <th>TRANS. NO.</th>
                                    <th>ROI</th>
                                    <th>DOCUMENT</th>
                                    <th>APPROVAL DATE</th>
                                    <th>TRANS. NO.</th>
                                    <th>RESPONSE</th>
                                    <th>STATUS</th>
                                    <th>REMARKS</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for material in object_list %}
                            <tr>
                                <td class="text-center">{{ material.ADNOC_documentno}}</td>
                              
                                <td class="text-center">{{ material.description }}</td>
                                <td class="text-center">{{ material.revision }}</td>
                                <td class="text-center">{{ material.due_date }}</td>
                                <td class="text-center">{{ material.submission_date }}</td>
                                <td class="text-center">{{ material.transmittal_number }}</td>
                                <td class="text-center">{{ material.reason_of_issue }}</td>
                                <td class="text-center"><a href="../media/{{material.document}}" target="_blank"><i class="nav-icon fas fa-copy"></i></a></td>
                                <td class="text-center">{{ material.aprroval_date }}</td>
                                <td class="text-center">{{ material.receipt_transmittalno }}</td>
                                <td class="text-center"><a href="../media/{{material.view_response}}" target="_blank"><i class="nav-icon fas fa-copy"></i></a></td>
                                <td class="text-center">{{ material.approval_code }}</td>
                                <td class="text-center">{{ material.remarks }}</td>
                                <td class="text-center">
                                    <i class="fa fa-pencil"
                                        onclick="edit_doc('{% url 'materials:get_doc' material.id %}')"></i>
                                </td>


                                
<!--  -->
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</section>
<script>
    function edit_doc(url) {
        $.getJSON(url,
            function (data) {
                console.log(data)
                var _data = JSON.parse(data);
                var __data = _data[0]['fields'];
                $("#_id").val(_data[0].pk);
                $("#id_ADNOC_documentno").val(__data.ADNOC_documentno);
                $("#id_description").val(__data.description);
                $("#id_revision").val(__data.revision);
                $("#id_due_date").val(__data.due_date);
                $("#id_submission_date").val(__data.submission_date);
                $("#id_transmittal_number").val(__data.transmittal_number);
                $("#id_reason_of_issue").val(__data.reason_of_issue);
                $("#id_document").val(__data.document);
                $("#id_aprroval_date").val(__data.aprroval_date);
                $("#id_receipt_transmittalno").val(__data.receipt_transmittalno);
                $("#id_view_response").val(__data.view_response);

                $("#id_approval_code").val(__data.approval_code);
                $("#id_remarks").val(__data.remarks);




            })
    }
</script>
{% endblock %}

src/materials/templates/materials/manage_materials.html
{% extends 'loggedbase.html' %}
{% load mathfilters %}
{% block title %}
Manage Materials
{% endblock %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body p-0">
                <h5 class="pt-2 pl-2"><i class="fa fa-search"></i> Search Material</h5>
                <hr>
                <form class="form-horizontal p-2" action="{% url 'materials:index' %}" method="GET" autocomplete="off"
                    novalidate>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="">Item Name</label>
                                <input type="text" id="item_s" name="item_s" class="form-control"
                                    value="{{request.GET.item_s}}" />
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="">Material</label>
                                <input type="text" id="material_s" name="material_s" class="form-control"
                                    value="{{request.GET.material_s}}" />
                            </div>
                        </div>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Search</button>
                        <a href="{% url 'materials:index' %}" class="btn btn-default btn-outline">Reset</a>
                        <a href="{% url 'materials:excel_export' %}" target="_blank" class="btn btn-success"><i
                                class="fa fa-file-pdf-o"></i> Export Excel</a>
                    </div>
                </form>
                {% for error in form.non_field_errors  %}
                <p class="text-danger text-center font-weight-bold mt-2">{{ error }}</p>
                {% endfor %}
                <form id="frm_material" action="{% url 'materials:index' %}" method="POST" autocomplete="off"
                    novalidate>
                    {% csrf_token %}
                    <table class="table table-sm">
                        <tr>
                            <input type="hidden" id="_id" name="_id" value="{{initial_id}}">
                            <th>{{form.item_s}}<span class="text-danger text-sm">{{form.item_s.errors.as_text}}</span>
                            </th>
                            <th>{{form.spec_s}}<span class="text-danger text-sm">{{form.spec_s.errors.as_text}}</span>
                            </th>
                            <th>{{form.material_s}}<span
                                    class="text-danger text-sm">{{form.material_s.errors.as_text}}</span>
                            </th>
                            <th>{{form.rating_s}}<span
                                    class="text-danger text-sm">{{form.rating_s.errors.as_text}}</span>
                            </th>
                            <th>{{form.size1_s}}<span class="text-danger text-sm">{{form.size1_s.errors.as_text}}</span>
                            </th>
                            <th>{{form.sch1_s}}<span class="text-danger text-sm">{{form.sch1_s.errors.as_text}}</span>
                            </th>
                            <th>{{form.size2_s}}<span class="text-danger text-sm">{{form.size2_s.errors.as_text}}</span>
                            </th>
                            <th>{{form.sch2_s}}<span class="text-danger text-sm">{{form.sch2_s.errors.as_text}}</span>
                            </th>
                            <th>{{form.facing_s}}<span
                                    class="text-danger text-sm">{{form.facing_s.errors.as_text}}</span>
                            </th>
                            <th class="text-center">-</th>
                            <th><input type="submit" name="" id="" class="btn btn-primary" value="Save"></th>
                        </tr>
                        <thead>
                            <tr>
                                <th width="18%">Item</th>
                                <th>Spec</th>
                                <th width="18%">Material</th>
                                <th>Rating</th>
                                <th>Size 1</th>
                                <th>Sch 1</th>
                                <th>Size 2</th>
                                <th>Sch 2</th>
                                <th>Facing</th>
                                <th>Quantity</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {%if materials %}
                            {% for material in materials %}
                            <tr>
                                <td>{{ material.item_s }}</td>
                                <td>{{ material.spec_s }}</td>
                                <td>{{ material.material_s }}</td>
                                <td>{{ material.rating_s }}</td>
                                <td>{{ material.size1_s }}</td>
                                <td>{{ material.sch1_s }}</td>
                                <td>{{ material.size2_s }}</td>
                                <td>{{ material.sch2_s }}</td>
                                <td>{{ material.facing_s }}</td>
                                <td class="text-center">
                                    <b>{% if material.po_quantity|sub:material.p_quantity != 0 and material.po_quantity|sub:material.p_quantity != '' %}{{material.po_quantity|sub:material.p_quantity}}{%else%}0{%endif%}</b>
                                </td>
                                <td class="text-center"><i class="fa fa-pencil"
                                        onclick="edit_material('{% url 'materials:get_material' material.id %}')"></i>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="10" class="text-center text-danger font-weight-bold">Material not found
                                </td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</section>
<script>
    function edit_material(url) {
        $.getJSON(url,
            function (data) {
                var _data = JSON.parse(data);
                var __data = _data[0]['fields'];
                $("#_id").val(_data[0].pk);
                $("#id_item_s").val(__data.item_s);
                $("#id_spec_s").val(__data.spec_s);
                $("#id_material_s").val(__data.material_s);
                $("#id_rating_s").val(__data.rating_s);
                $("#id_size1_s").val(__data.size1_s);
                $("#id_sch1_s").val(__data.sch1_s);
                $("#id_size2_s").val(__data.size2_s);
                $("#id_sch2_s").val(__data.sch2_s);
                $("#id_facing_s").val(__data.facing_s);
            })
    }
</script>
{% endblock %}