src/chart/urls.py
from django.conf.urls import url
from .views import TaskView
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^(?P<s_id>\d+)/$', TemplateView.as_view(template_name='gantt.html'), name='ganttchart'),
    url(r'^task/(?P<schedule_id>\d+)/$', TaskView.as_view())
]

src/projects/urls.py
from django.urls import path
from .view import *
app_name = "projects"

urlpatterns = [
    path('', index, name="index"),
    path('transfer', transfer, name="transfer"),
    path('<int:id>', get_project, name="get_project"),
    path('items/<int:id>', items, name="items"),
    path('item/<int:id>', get_project_item, name="get_project_item"),
    path('pending_material_report', pending_material_report,
         name="pending_material_report"),
    path('missing_material_report', missing_material_report,
         name="missing_material_report"),
    path('approval_request', approval_request, name="approval_request"),
    path('approve_item/<int:id>', approve_item, name="approve_item"),
    path('transfer_report', transfer_report, name="transfer_report"),
    path('pdf_report/<int:id>', pdf_report, name="pdf_report"),

    path('project_activity/<int:id>', get_project_activity,
         name="get_project_activity"),

    path('update_project_activity_plan', update_project_activity_plan,
         name="update_project_activity_plan"),
    path('excel_activity', excel_activity, name="excel_activity"),
    path('get_project_activity_plan_by_year_month', get_project_activity_plan_by_year_month,
         name="get_project_activity_plan_by_year_month"),
    path('project_activity', project_activity, name="project_activity"),
    path('create_activity', create_activity, name="create_activity"),
    path('edit_activity', edit_activity, name="edit_activity"),
    path('plans/<int:id>', plans, name="plans"),
    path('set_plan_fixed/<int:id>', set_plan_fixed, name="set_plan_fixed"),
    path('update_revisor/<int:id>', update_revisor, name="update_revisor"),
    path('get_project_activity_plan/<int:id>',
         get_project_activity_plan, name="get_project_activity_plan"),
    path('revise_plans', revise_plans, name="revise_plans"),
    path('revised_plan_report', revised_plan_report, name="revised_plan_report"),
    path('revise_plan/<int:id>', revise_plan, name="revise_plan"),
    path('chart_report', chart_report, name="chart_report"),
    path('edit_schedule_info', edit_schedule_info, name="edit_schedule_info"),
]

src/trackpot/urls.py
from django.contrib import admin
from django.urls import path, include
from projects.views import register_view
from projects.views import home_view, en_upload_SG_view
from django.contrib.auth import views as auth_views
from materials.views import register_store_view
from django.conf.urls import url
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from django.conf.urls.static import static
from chart.views import TaskView
from django.contrib.auth.decorators import login_required
from users.views import logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('register/', register_view, name='register'),
    path('home/', home_view, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),


    path('materials/',include('materials.urls')),
    path('purchase_orders/',include('purchase_orders.urls')),
    path('projects/',include('projects.urls')),




    # path('logout/',auth_views.LogoutView.as_view(template_name= 'users/logout.html'), name='logout'),
    # path('registerSpools/',register_spools_view , name='registerSpools'),
    # re_path(r'^(?P<page_id>[0-9]+)/$', subproject_view, name='pagedetail'),
    re_path('chart/', include('chart.urls'), name='ganttchart'),
    re_path(r'^task/(?P<schedule_id>\d+)/$',
            login_required(TaskView.as_view()), name='gchart'),
    re_path('storeview/', register_store_view, name='Store'),

    # url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    #  url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})

    #path('registerProject/',complete_project_view , name='Projectlist'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path(r'media/(?P<path>.*)$',
                serve, {'document_root': settings.MEDIA_ROOT, }),
    ]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += [
#         re_path(r'^media/(?P<path>.*)$', serve, {
#             'document_root': settings.MEDIA_ROOT,
#         }),
#     ]

src/projects/models.py
from django.db import models
from django.utils import timezone
from materials.models import Store
from django.conf import settings
from chart.models import Schedule
# Create your models here.


class Project(models.Model):
    receipt_number = models.CharField(max_length=32)
    contract_name = models.CharField(max_length=100, blank=True, null=True)
    description = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=191, blank=True, null=True)
    delivery_date = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    schedule = models.ForeignKey(
        Schedule, null=True, blank=True, on_delete=models.SET_NULL)
    assigned_for = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)


class ProjectItem(models.Model):
    quantity = models.IntegerField(default=0)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    item = models.ForeignKey(Store, on_delete=models.CASCADE, null=True)
    is_pending = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)


class ProjectMissingItem(models.Model):
    quantity = models.IntegerField(default=0)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    item = models.ForeignKey(Store, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)


class ProjectActivity(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)
    weightage = models.FloatField(blank=False, null=False)
    schedule = models.ForeignKey(
        Schedule, null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(default=timezone.now)
    revisor = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)


class ProjectActivityPlan(models.Model):
    plan_year = models.CharField(max_length=4, blank=False, null=False)
    plan_month = models.CharField(max_length=3, blank=False, null=False)
    plan_value = models.FloatField()
    actual_value = models.FloatField()
    is_plan_fixed = models.BooleanField(default=False)
    project_activity = models.ForeignKey(
        ProjectActivity, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)


class ProjectActivityPlanLog(models.Model):
    old_plan_value = models.FloatField()
    project_activity_plan = models.ForeignKey(
        ProjectActivityPlan, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)


class ScheduleInfo(models.Model):
    schedule = models.ForeignKey(
        Schedule, null=True, blank=True, on_delete=models.SET_NULL)
    project_description = models.CharField(
        max_length=191, blank=True, null=True)
    project_date = models.DateField(blank=True, null=True)
    weekly_progress = models.CharField(max_length=191, blank=True, null=True)
    cummlative_progress = models.CharField(
        max_length=191, blank=True, null=True)
    variance = models.CharField(max_length=191, blank=True, null=True)
    progress_statistic = models.CharField(
        max_length=191, blank=True, null=True)
    procurement = models.CharField(max_length=191, blank=True, null=True)
    mdr = models.CharField(max_length=191, blank=True, null=True)
    fabrication = models.CharField(max_length=191, blank=True, null=True)
    installation = models.CharField(max_length=191, blank=True, null=True)
    reason_for_variance = models.CharField(
        max_length=191, blank=True, null=True)
    detailed_progress_for_week = models.CharField(
        max_length=191, blank=True, null=True)
    planned_progress_for_next_week = models.CharField(
        max_length=191, blank=True, null=True)
    area_of_concerns = models.CharField(max_length=191, blank=True, null=True)


class ScheduleDocument(models.Model):
    schedule = models.ForeignKey(
        Schedule, null=True, blank=True, on_delete=models.SET_NULL)
    file_url = models.FileField(upload_to='schedule_files/')
    created_at = models.DateTimeField(default=timezone.now)

src/materials/forms.py
from django import forms
from chart.models import Schedule
from .models import Store


class MaterialForm(forms.ModelForm):
    item_s = forms.CharField(required=True,label='Item',max_length="100",widget=forms.TextInput(attrs={'class': 'form-control'}))
    spec_s = forms.CharField(required=False,label='Spec',max_length="100",widget=forms.TextInput(attrs={'class': 'form-control'}))
    material_s = forms.CharField(required=True,label='Material',max_length="100",widget=forms.TextInput(attrs={'class': 'form-control'}))
    rating_s = forms.CharField(required=False,label='',max_length="100",widget=forms.TextInput(attrs={'class': 'form-control'}))
    size1_s = forms.IntegerField(required=True,label='',widget=forms.TextInput(attrs={'class': 'form-control'}))
    sch1_s = forms.IntegerField(required=False,label='',widget=forms.TextInput(attrs={'class': 'form-control'}))
    size2_s = forms.IntegerField(required=False,label='',widget=forms.TextInput(attrs={'class': 'form-control'}))
    sch2_s = forms.IntegerField(required=False,label='',widget=forms.TextInput(attrs={'class': 'form-control'}))
    facing_s = forms.CharField(required=True,label='',max_length="100",widget=forms.TextInput(attrs={'class': 'form-control'}))
    
    class Meta:
        model=Store
        fields = ["item_s","spec_s","material_s","rating_s","size1_s","sch1_s","size2_s","sch2_s","facing_s"]

    def clean(self):
        rating = self.cleaned_data.get("rating_s")
        sch1 = self.cleaned_data.get("sch1_s")
        if rating is None:
            if sch1 is None:
                raise forms.ValidationError("Schedule 1 field is required!")
        if sch1 is None:
            if rating is None:
                raise forms.ValidationError("Rating field is required!")

class StoreRegisterForm(forms.ModelForm):


    class Meta:
        model=Store
        fields= ["item_s",'spec_s',
                "material_s",
                "rating_s",
                "size1_s" ,
                "sch1_s",
                "size2_s",
                "sch2_s",
                "facing_s",
            ]





class ProjectRegisterForm(forms.ModelForm):


    class Meta:
        model=Schedule
        fields= ['name','start_date','end_date','progress_schedule']

src/projects/views.py
from django.shortcuts import render,redirect
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from .forms import UserRegisterForm
from materials.forms import ProjectRegisterForm
# from materials.models import Proj
from chart.models import Schedule
from users.forms import UserRegisterForm
from django.contrib.auth.decorators import login_required


# Create your views here.
# def register_project_view(request,*args,**kwargs):

# 	if request.method=='POST':
# 			form = ProjectRegisterForm(request.POST)
# 			if form.is_valid():
# 				form.save()
				
# 				return redirect('RequirementList')
# 	else:
# 		form=ProjectRegisterForm()
# 	return form

@login_required()
def home_view(request,*args,**kwargs):
	# class table_view(ListView):
	# template_name="materials/listview.html"
	# queryset = Requirement.objects.all()
	schedule_list = Schedule.objects.filter(added_by=request.user)
	if not schedule_list:
		first_project = Schedule(name="Sample Project",is_selected=True,added_by=request.user,progress_schedule=0)
		first_project.save()
		print('saved')


	else:
		
		project_id = request.GET.get('project')
		first_project= schedule_list.first()
		first_project.is_selected=True
		first_project.save()
	
	project_selected = Schedule.objects.filter(added_by=request.user,is_selected=True)
	
	
	if request.method == 'GET' and 'project' in request.GET:
		q = request.GET['project']
		if q is not None and q != '':	
			project_selected = Schedule.objects.filter(added_by=request.user,id=project_id)
			for project in schedule_list:
				project.is_selected=False
				project.save()
			
				
			for project in project_selected:
				first_project.is_selected=False
				first_project.save()
				project.is_selected=True
				project.save()
	# object_list = Proj.objects.all()
			
	if request.method=='POST':
			form = ProjectRegisterForm(request.POST)
    
        	
			if form.is_valid():
				obj = form.save()
				obj.added_by = request.user
				obj.save()
				# return redirect('pagedetail', page_id=obj.id)
				return redirect('home')
	else:
		form=ProjectRegisterForm()

	if request.method=='POST':
			form1 = UserRegisterForm(request.POST)
			if form1.is_valid():
				save_it = form1.save()
				save_it.save()
				# subject="Thanks for registering with us"
				# message = "welcome "
				# from_email = settings.EMAIL_HOST_USER
				# to_list = [save_it.email , settings.EMAIL_HOST_USER]
				# send_mail(subject,message,from_email,to_list)
				# to turn off errors add fail_silently = True as an arguement to send_mail
				username=form1.cleaned_data.get('username');
				messages.success(request,f'Account created for {username}.')
				return redirect('home')
	else:
		form1=UserRegisterForm()
	selected_project= project_selected.first()

	context = {
	# 'object_list' : object_list,
	'form' : form,
	'form1' : form1,
	'schedule_list' : schedule_list,
	'project_selected' : project_selected,
	'project_list_first': selected_project

	}
	return render(request,"projects/home.html",context)

@login_required()
def en_upload_SG_view(request,*args,**kwargs):
	return render(request,"projects/en-upload-SG.html",{})
@login_required()
def register_view(request,*args,**kwargs):
	if request.method=='POST':
			form = UserRegisterForm(request.POST)
			if form.is_valid():
				save_it = form.save()
				save_it.save()
				subject="Thanks for registering with us"
				message = "welcome "
				from_email = settings.EMAIL_HOST_USER
				to_list = [save_it.email , settings.EMAIL_HOST_USER]
				send_mail(subject,message,from_email,to_list)
				# to turn off errors add fail_silently = True as an arguement to send_mail
				username=form.cleaned_data.get('username');
				messages.success(request,f'Account created for {username}.')
				return redirect('register')
	else:
		form=UserRegisterForm()
	return render(request,"projects/register.html",{'form':form})

src/projects/templates/projects/editproject.html
{% extends 'loggedbase.html'%}
{% block link %} <a href="{% url 'ganttchart' project_list_first.id %}" class="nav-link" target="_blank">{% endblock %}


{% load crispy_forms_tags %}
{%block content%}
  

<div class="jumbotron" style="width: 500px; margin: 0 auto;">
<h1 id="loginh1">Edit project: {{editproj}}</h1>

<form method="POST" id="login" >
  {%csrf_token%}

  <fieldset class="form group">
  {{form|crispy}}
  </fieldset>
  
  <div class="form-group">
    <button type="submit" class="btn btn-outline-info">Update</button>
  </div>
   <!-- <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="#">Sign In</a>
            </small>
        </div> -->
</form>
</div>
{%endblock%}

src/projects/templates/projects/manage_project_activity.html
{% extends 'loggedbase.html' %}
{% block title %}
Manage Projects for {{schedule.name}}
{% endblock %}
{% block content %}
<section class="content">
    <form class="form-horizontal" method="POST" action="{% url 'projects:project_activity' %}">
        {% csrf_token %}
        {{ formset.management_form }}
        {%for err in formset.non_form_errors%}
        <div class="text-danger text-center">{{err}}</div>
        {% endfor %}
        <table class="table table-bordered" id="activity_table">

            <thead>
                <tr>
                    <td>Activity Name</td>
                    <td>Weightage</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
                {% for form in formset %}
                <tr>
                    <td>{{form.name}}</td>
                    <td>{{form.weightage}}{{form.id}}</td>
                    <td></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="javascript:void(0);" class="btn btn-info" onclick="add_new_row()">Add new row</a>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</section>
<script>
    function edit_project(url) {
        $.getJSON(url,
            function (data) {
                console.log(data)
                //var _data = JSON.parse(data);
                var __data = data['project'][0];
                $("#_id").val(__data.id);
                $("#id_receipt_number").val(__data.receipt_number);
                $("#id_contract_name").val(__data.contract_name);
                $("#id_address").val(__data.address);
                $("#id_assigned_for").val(data.username);
                $("#id_description").val(__data.description);
                if (__data.delivery_date) {
                    var _delivery_date = new Date(__data.delivery_date);
                    var _date = _delivery_date.getDate().toLocaleString().length == 1 ? '0' + _delivery_date
                        .getDate() :
                        _delivery_date.getDate();
                    var __month = Number(_delivery_date.getMonth() + 1);
                    var _month = _delivery_date.getMonth().toLocaleString().length == 1 ? '0' + __month : __month;
                    $("#id_delivery_date").val(_date + "-" + _month + "-" +
                        _delivery_date.getFullYear());
                }
            })
    }
</script>
{% endblock %}
{% block js_scripts%}
<script type='text/javascript'>
    $(document).ready(function () {

    });

    function escapeRegExp(string) {
        return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    }

    function replaceAll(str, term, replacement) {
        return str.replace(new RegExp(escapeRegExp(term), 'g'), replacement);
    }

    function add_new_row() {
        var last_row = $("#activity_table tbody tr:nth-last-child(1)").html();
        var _last_row = $("#activity_table tbody tr:nth-last-child(1) td:nth-child(1)").html();
        var _id = $.parseHTML(_last_row)[0].id;
        _id = _id.substring(8)
        _id = _id.slice(0, -5);
        nextId = Number(_id) + 1;
        var updatedHTML = replaceAll(last_row, "form-" + _id, "form-" + nextId)
        $("#activity_table tbody").append("<tr>" + updatedHTML + "</tr>");
        $('#id_form-TOTAL_FORMS').val(Number(nextId) + 1);
    }
</script>
{% endblock %}

src/projects/templates/projects/manage_projects.html
{% extends 'loggedbase.html' %}
{% block title %}
Manage Projects for {{schedule.name}}
{% endblock %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body p-0">
                <h5 class="pt-2 pl-2"><i class="fa fa-search"></i> Search Project</h5>
                <hr>
                <form class="form-horizontal p-2" action="{% url 'projects:index' %}" method="GET" autocomplete="off"
                    novalidate>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="">Receipt Number</label>
                                <input type="text" id="receipt_number" name="receipt_number" class="form-control"
                                    value="{{request.GET.receipt_number}}" />
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="">Project Name</label>
                                <input type="text" id="name" name="name" class="form-control"
                                    value="{{request.GET.name}}" />
                            </div>
                        </div>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Search</button>
                        <a href="{% url 'projects:index' %}" class="btn btn-default btn-outline">Reset</a>
                    </div>
                </form>
                <form id="frm_project" action="{% url 'projects:index' %}" method="POST" autocomplete="off" novalidate>
                    {% csrf_token %}
                    <table class="table table-sm">
                        <tr>
                            <input type="hidden" id="_id" name="_id" value="{{initial_id}}">
                            <th>{{form.receipt_number}}<span
                                    class="text-danger text-sm">{{form.receipt_number.errors.as_text}}</span>
                            </th>
                            <th>{{form.contract_name}}<span
                                    class="text-danger text-sm">{{form.contract_name.errors.as_text}}</span>
                            </th>
                            <th>{{form.address}}<span class="text-danger text-sm">{{form.address.errors.as_text}}</span>
                            <th>{{form.description}}<span
                                    class="text-danger text-sm">{{form.description.errors.as_text}}</span>
                            <th>{{form.delivery_date}}<span
                                    class="text-danger text-sm">{{form.delivery_date.errors.as_text}}</span>
                            </th>
                            <th>{{form.assigned_for}}<span
                                    class="text-danger text-sm">{{form.assigned_for.errors.as_text}}</span>
                            </th>
                            <th><input type="submit" name="" id="" class="btn btn-primary" value="Save"></th>
                        </tr>
                        <thead>
                            <tr>
                                <th>Receipt No.</th>
                                <th>Contract Name</th>
                                <th>Address</th>
                                <th>Description</th>
                                <th>Delivery Date</th>
                                <th>Assigned For</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for project in projects %}
                            <tr>
                                <td>{{ project.receipt_number }}</td>
                                <td>{{ project.contract_name }}</td>
                                <td>{{ project.address }}</td>
                                <td>{{ project.description }}</td>
                                <td>{{ project.delivery_date|date:'d-m-Y' }}</td>
                                <td>{{ project.assigned_for.username }}</td>
                                <td class="text-center">
                                    <i class="fa fa-pencil"
                                        onclick="edit_project('{% url 'projects:get_project' project.id %}')"></i>
                                    <a href="{% url 'projects:items' project.id %}"><i class="ml-2 fa fa-plus"></i></a>
                                    <a class="text-info" target="_blank"
                                        href="{% url 'projects:pdf_report' project.id %}"><i
                                            class="ml-2 fa fa-file-pdf-o"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</section>
<script>
    function edit_project(url) {
        $.getJSON(url,
            function (data) {
                console.log(data)
                //var _data = JSON.parse(data);
                var __data = data['project'][0];
                $("#_id").val(__data.id);
                $("#id_receipt_number").val(__data.receipt_number);
                $("#id_contract_name").val(__data.contract_name);
                $("#id_address").val(__data.address);
                $("#id_assigned_for").val(data.username);
                $("#id_description").val(__data.description);
                if (__data.delivery_date) {
                    var _delivery_date = new Date(__data.delivery_date);
                    var _date = _delivery_date.getDate().toLocaleString().length == 1 ? '0' + _delivery_date
                        .getDate() :
                        _delivery_date.getDate();
                    var __month = Number(_delivery_date.getMonth() + 1);
                    var _month = _delivery_date.getMonth().toLocaleString().length == 1 ? '0' + __month : __month;
                    $("#id_delivery_date").val(_date + "-" + _month + "-" +
                        _delivery_date.getFullYear());
                }
            })
    }
</script>
{% endblock %}

src/projects/templates/projects/project-material.html
{% extends 'loggedbase.html' %}
{% block link %} <a href="{% url 'ganttchart' project_list_first.id %}" class="nav-link" target="_blank">{% endblock %}

{% load mathfilters %}
{% block title %}
Manage Materials
{% endblock %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body p-0">
                <h5 class="pt-2 pl-2"><i class="fa fa-search"></i> Search Material</h5>
                <hr>
                <form class="form-horizontal p-2" action="{% url 'projects:project_materials' %}" method="GET" autocomplete="off"
                    novalidate>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="">Item Name</label>
                                <input type="text" id="item_s" name="item_s" class="form-control"
                                    value="{{request.GET.item_s}}" />
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="">Material</label>
                                <input type="text" id="material_s" name="material_s" class="form-control"
                                    value="{{request.GET.material_s}}" />
                            </div>
                        </div>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Search</button>
                        <a href="{% url 'projects:project_materials' %}" class="btn btn-default btn-outline">Reset</a>
                        <a href="{% url 'projects:export_excel' %}" target="_blank" class="btn btn-success"><i
                                class="fa fa-file-pdf-o"></i> Export Excel</a>
                    </div>
                </form>
                
                <p class="text-danger text-center font-weight-bold mt-2">{{ error }}</p>
               
               
                  
                    <table class="table table-sm">
                       
                        <thead>
                            <tr>
                                <th width="18%">Item</th>
                                <th>Spec</th>
                                <th width="18%">Material</th>
                                <th>Rating</th>
                                <th>Size 1</th>
                                <th>Sch 1</th>
                                <th>Size 2</th>
                                <th>Sch 2</th>
                                <th>Facing</th>
                                <th>Quantity</th>
                               
                            </tr>
                        </thead>
                        <tbody>
                            {%if materials %}
                            {% for material in materials %}
                            <tr>
                                <td>{{ material.item.item_s }}</td>
                                <td>{{ material.item.spec_s }}</td>
                                <td>{{ material.item.material_s }}</td>
                                <td>{{ material.item.rating_s }}</td>
                                <td>{{ material.item.size1_s }}</td>
                                <td>{{ material.item.sch1_s }}</td>
                                <td>{{ material.item.size2_s }}</td>
                                <td>{{ material.item.sch2_s }}</td>
                                <td>{{ material.item.facing_s }}</td>
                                <td>
                                    <b>{{material.quantity}}</b>
                                </td>
                                
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="10" class="text-center text-danger font-weight-bold">Material not found
                                </td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</section>
<script>
    function edit_material(url) {
        $.getJSON(url,
            function (data) {
                var _data = JSON.parse(data);
                var __data = _data[0]['fields'];
                $("#_id").val(_data[0].pk);
                $("#id_item_s").val(__data.item_s);
                $("#id_spec_s").val(__data.spec_s);
                $("#id_material_s").val(__data.material_s);
                $("#id_rating_s").val(__data.rating_s);
                $("#id_size1_s").val(__data.size1_s);
                $("#id_sch1_s").val(__data.sch1_s);
                $("#id_size2_s").val(__data.size2_s);
                $("#id_sch2_s").val(__data.sch2_s);
                $("#id_facing_s").val(__data.facing_s);
            })
    }
</script>
{% endblock %}

src/projects/templates/projects/stock_not_available.html
<a href="{% url 'projects:approval_request' %}">Back</a>
<h1>Stock not available</h1>